USE [BEERWULF]
GO
/****** Object:  Table [dbo].[ORDERS]    Script Date: 30.06.2021 02:08:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDERS](
	[O_ORDERKEY] [int] NOT NULL,
	[O_CUSTKEY] [int] NOT NULL,
	[O_ORDERSTATUS] [text] NOT NULL,
	[O_TOTALPRICE] [decimal](18, 2) NOT NULL,
	[O_ORDERDATE] [date] NOT NULL,
	[O_ORDERPRIORITY] [text] NOT NULL,
	[O_CLERK] [text] NOT NULL,
	[O_SHIPPRIORITY] [int] NOT NULL,
	[O_COMMENT] [text] NOT NULL,
 CONSTRAINT [PK__ORDERS__AAA6619DC34E115C] PRIMARY KEY CLUSTERED 
(
	[O_ORDERKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LINEITEM]    Script Date: 30.06.2021 02:08:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LINEITEM](
	[L_ORDERKEY] [int] NOT NULL,
	[L_PARTKEY] [int] NOT NULL,
	[L_SUPPKEY] [int] NOT NULL,
	[L_LINENUMBER] [int] NOT NULL,
	[L_QUANTITY] [int] NOT NULL,
	[L_EXTENDEDPRICE] [decimal](18, 2) NOT NULL,
	[L_DISCOUNT] [decimal](18, 2) NOT NULL,
	[L_TAX] [decimal](18, 2) NOT NULL,
	[L_RETURNFLAG] [text] NOT NULL,
	[L_LINESTATUS] [text] NOT NULL,
	[L_SHIPDATE] [date] NOT NULL,
	[L_COMMITDATE] [date] NOT NULL,
	[L_RECEIPTDATE] [date] NOT NULL,
	[L_SHIPINSTRUCT] [text] NOT NULL,
	[L_SHIPMODE] [text] NOT NULL,
	[L_COMMENT] [text] NOT NULL,
	[L_LINEITEMKEY] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK__LINEITEM__DD1C9C94F5AF4BEE] PRIMARY KEY CLUSTERED 
(
	[L_ORDERKEY] ASC,
	[L_LINENUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  View [dbo].[W_ClusteringData]    Script Date: 30.06.2021 02:08:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[W_ClusteringData]
AS
SELECT        O.O_CUSTKEY, SUM(L.L_QUANTITY) AS QUANTITY, SUM(L.L_EXTENDEDPRICE) AS EXTENDEDPRICE
FROM            dbo.LINEITEM AS L INNER JOIN
                         dbo.ORDERS AS O ON L.L_ORDERKEY = O.O_ORDERKEY
GROUP BY O.O_CUSTKEY
GO
/****** Object:  Table [dbo].[CUSTOMER]    Script Date: 30.06.2021 02:08:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMER](
	[C_CUSTKEY] [int] NOT NULL,
	[C_NAME] [text] NOT NULL,
	[C_ADDRESS] [text] NOT NULL,
	[C_NATIONKEY] [int] NOT NULL,
	[C_PHONE] [text] NOT NULL,
	[C_ACCTBAL] [decimal](18, 2) NOT NULL,
	[C_MKTSEGMENT] [text] NOT NULL,
	[C_COMMENT] [text] NOT NULL,
 CONSTRAINT [PK__CUSTOMER__DA976F94C05832A0] PRIMARY KEY CLUSTERED 
(
	[C_CUSTKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NATION]    Script Date: 30.06.2021 02:08:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NATION](
	[N_NATIONKEY] [int] NOT NULL,
	[N_NAME] [text] NOT NULL,
	[N_REGIONKEY] [int] NOT NULL,
	[N_COMMENT] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[N_NATIONKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PART]    Script Date: 30.06.2021 02:08:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PART](
	[P_PARTKEY] [int] NOT NULL,
	[P_NAME] [text] NOT NULL,
	[P_MFGR] [text] NOT NULL,
	[P_BRAND] [text] NOT NULL,
	[P_TYPE] [text] NOT NULL,
	[P_SIZE] [int] NOT NULL,
	[P_CONTAINER] [text] NOT NULL,
	[P_RETAILPRICE] [decimal](18, 2) NOT NULL,
	[P_COMMENT] [text] NOT NULL,
 CONSTRAINT [PK__PART__7FC1E95F80E7DCA1] PRIMARY KEY CLUSTERED 
(
	[P_PARTKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PARTSUPP]    Script Date: 30.06.2021 02:08:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARTSUPP](
	[PS_PARTKEY] [int] NOT NULL,
	[PS_SUPPKEY] [int] NOT NULL,
	[PS_AVAILQTY] [int] NOT NULL,
	[PS_SUPPLYCOST] [decimal](18, 2) NOT NULL,
	[PS_COMMENT] [text] NOT NULL,
 CONSTRAINT [PK__PARTSUPP__54937F69EF9C674F] PRIMARY KEY CLUSTERED 
(
	[PS_PARTKEY] ASC,
	[PS_SUPPKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REGION]    Script Date: 30.06.2021 02:08:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REGION](
	[R_REGIONKEY] [int] NOT NULL,
	[R_NAME] [text] NOT NULL,
	[R_COMMENT] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[R_REGIONKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SEGMENT]    Script Date: 30.06.2021 02:08:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SEGMENT](
	[SEG_CUSTKEY] [int] NOT NULL,
	[SEG_SEGMENT] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SEG_CUSTKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ST_F_LINEITEM]    Script Date: 30.06.2021 02:08:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ST_F_LINEITEM](
	[L_LINEITEMKEY] [int] NOT NULL,
	[L_LINENUMBER] [int] NOT NULL,
	[L_ORDERKEY] [int] NOT NULL,
	[L_PARTKEY] [int] NOT NULL,
	[L_SUPPKEY] [int] NOT NULL,
 CONSTRAINT [PK_ST_F_LINEITEM] PRIMARY KEY CLUSTERED 
(
	[L_LINEITEMKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUPPLIER]    Script Date: 30.06.2021 02:08:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUPPLIER](
	[S_SUPPKEY] [int] NOT NULL,
	[S_NAME] [text] NOT NULL,
	[S_ADDRESS] [text] NOT NULL,
	[S_NATIONKEY] [int] NOT NULL,
	[S_PHONE] [text] NOT NULL,
	[S_ACCTBAL] [decimal](18, 2) NOT NULL,
	[S_COMMENT] [text] NOT NULL,
 CONSTRAINT [PK__SUPPLIER__3632082BA150F2A8] PRIMARY KEY CLUSTERED 
(
	[S_SUPPKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_D_LINEITEM]    Script Date: 30.06.2021 02:08:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_D_LINEITEM](
	[LINEITEMKEY] [int] NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[EXTENDEDPRICE] [decimal](18, 2) NOT NULL,
	[DISCOUNT] [decimal](18, 2) NOT NULL,
	[TAX] [decimal](18, 2) NOT NULL,
	[RETURNFLAG] [text] NOT NULL,
	[LINESTATUS] [text] NOT NULL,
	[SHIPDATE] [date] NOT NULL,
	[COMMITDATE] [date] NOT NULL,
	[RECEIPTDATE] [date] NOT NULL,
	[SHIPINSTRUCT] [text] NOT NULL,
	[SHIPMODE] [text] NOT NULL,
	[COMMENT] [text] NOT NULL,
	[REVENUE] [decimal](38, 6) NOT NULL,
 CONSTRAINT [PK_T_D_LINEITEM] PRIMARY KEY CLUSTERED 
(
	[LINEITEMKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_F_LINEITEM]    Script Date: 30.06.2021 02:08:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_F_LINEITEM](
	[LINEITEMKEY] [int] NULL,
	[ORDERKEY] [int] NULL,
	[PARTKEY] [int] NULL,
	[SUPPKEY] [int] NULL,
	[CUSTKEY] [int] NULL,
	[CUST_REGIONKEY] [int] NULL,
	[CUST_NATIONKEY] [int] NULL,
	[SUPP_REGIONKEY] [int] NULL,
	[SUPP_NATIONKEY] [int] NULL,
	[LINENUMBER] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[XYZ]    Script Date: 30.06.2021 02:08:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[XYZ](
	[LINENUMBERKEY] [int] NULL,
	[ORDERKEY] [int] NOT NULL,
	[PARTKEY] [int] NOT NULL,
	[SUPPKEY] [int] NOT NULL,
	[O_CUSTKEY] [int] NULL,
	[CUST_REGIONKEY] [int] NULL,
	[CUST_NATIONKEY] [int] NULL,
	[SUPP_REGIONKEY] [int] NULL,
	[SUPP_NATIONKEY] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LINEITEM]  WITH CHECK ADD  CONSTRAINT [FK__LINEITEM__4BAC3F29] FOREIGN KEY([L_PARTKEY], [L_SUPPKEY])
REFERENCES [dbo].[PARTSUPP] ([PS_PARTKEY], [PS_SUPPKEY])
GO
ALTER TABLE [dbo].[LINEITEM] CHECK CONSTRAINT [FK__LINEITEM__4BAC3F29]
GO
ALTER TABLE [dbo].[LINEITEM]  WITH CHECK ADD  CONSTRAINT [FK__LINEITEM__L_ORDE__4AB81AF0] FOREIGN KEY([L_ORDERKEY])
REFERENCES [dbo].[ORDERS] ([O_ORDERKEY])
GO
ALTER TABLE [dbo].[LINEITEM] CHECK CONSTRAINT [FK__LINEITEM__L_ORDE__4AB81AF0]
GO
ALTER TABLE [dbo].[T_F_LINEITEM]  WITH CHECK ADD  CONSTRAINT [FK_T_F_LINEITEM_CUSTOMER] FOREIGN KEY([CUSTKEY])
REFERENCES [dbo].[CUSTOMER] ([C_CUSTKEY])
GO
ALTER TABLE [dbo].[T_F_LINEITEM] CHECK CONSTRAINT [FK_T_F_LINEITEM_CUSTOMER]
GO
ALTER TABLE [dbo].[T_F_LINEITEM]  WITH CHECK ADD  CONSTRAINT [FK_T_F_LINEITEM_NATION] FOREIGN KEY([CUST_NATIONKEY])
REFERENCES [dbo].[NATION] ([N_NATIONKEY])
GO
ALTER TABLE [dbo].[T_F_LINEITEM] CHECK CONSTRAINT [FK_T_F_LINEITEM_NATION]
GO
ALTER TABLE [dbo].[T_F_LINEITEM]  WITH CHECK ADD  CONSTRAINT [FK_T_F_LINEITEM_NATION1] FOREIGN KEY([SUPP_NATIONKEY])
REFERENCES [dbo].[NATION] ([N_NATIONKEY])
GO
ALTER TABLE [dbo].[T_F_LINEITEM] CHECK CONSTRAINT [FK_T_F_LINEITEM_NATION1]
GO
ALTER TABLE [dbo].[T_F_LINEITEM]  WITH CHECK ADD  CONSTRAINT [FK_T_F_LINEITEM_ORDERS] FOREIGN KEY([ORDERKEY])
REFERENCES [dbo].[ORDERS] ([O_ORDERKEY])
GO
ALTER TABLE [dbo].[T_F_LINEITEM] CHECK CONSTRAINT [FK_T_F_LINEITEM_ORDERS]
GO
ALTER TABLE [dbo].[T_F_LINEITEM]  WITH CHECK ADD  CONSTRAINT [FK_T_F_LINEITEM_PART] FOREIGN KEY([PARTKEY])
REFERENCES [dbo].[PART] ([P_PARTKEY])
GO
ALTER TABLE [dbo].[T_F_LINEITEM] CHECK CONSTRAINT [FK_T_F_LINEITEM_PART]
GO
ALTER TABLE [dbo].[T_F_LINEITEM]  WITH CHECK ADD  CONSTRAINT [FK_T_F_LINEITEM_PARTSUPP] FOREIGN KEY([PARTKEY], [SUPPKEY])
REFERENCES [dbo].[PARTSUPP] ([PS_PARTKEY], [PS_SUPPKEY])
GO
ALTER TABLE [dbo].[T_F_LINEITEM] CHECK CONSTRAINT [FK_T_F_LINEITEM_PARTSUPP]
GO
ALTER TABLE [dbo].[T_F_LINEITEM]  WITH CHECK ADD  CONSTRAINT [FK_T_F_LINEITEM_REGION] FOREIGN KEY([CUST_REGIONKEY])
REFERENCES [dbo].[REGION] ([R_REGIONKEY])
GO
ALTER TABLE [dbo].[T_F_LINEITEM] CHECK CONSTRAINT [FK_T_F_LINEITEM_REGION]
GO
ALTER TABLE [dbo].[T_F_LINEITEM]  WITH CHECK ADD  CONSTRAINT [FK_T_F_LINEITEM_REGION1] FOREIGN KEY([SUPP_REGIONKEY])
REFERENCES [dbo].[REGION] ([R_REGIONKEY])
GO
ALTER TABLE [dbo].[T_F_LINEITEM] CHECK CONSTRAINT [FK_T_F_LINEITEM_REGION1]
GO
ALTER TABLE [dbo].[T_F_LINEITEM]  WITH CHECK ADD  CONSTRAINT [FK_T_F_LINEITEM_SEGMENT] FOREIGN KEY([CUSTKEY])
REFERENCES [dbo].[SEGMENT] ([SEG_CUSTKEY])
GO
ALTER TABLE [dbo].[T_F_LINEITEM] CHECK CONSTRAINT [FK_T_F_LINEITEM_SEGMENT]
GO
ALTER TABLE [dbo].[T_F_LINEITEM]  WITH CHECK ADD  CONSTRAINT [FK_T_F_LINEITEM_ST_F_LINEITEM] FOREIGN KEY([LINEITEMKEY])
REFERENCES [dbo].[ST_F_LINEITEM] ([L_LINEITEMKEY])
GO
ALTER TABLE [dbo].[T_F_LINEITEM] CHECK CONSTRAINT [FK_T_F_LINEITEM_ST_F_LINEITEM]
GO
ALTER TABLE [dbo].[T_F_LINEITEM]  WITH CHECK ADD  CONSTRAINT [FK_T_F_LINEITEM_SUPPLIER] FOREIGN KEY([SUPPKEY])
REFERENCES [dbo].[SUPPLIER] ([S_SUPPKEY])
GO
ALTER TABLE [dbo].[T_F_LINEITEM] CHECK CONSTRAINT [FK_T_F_LINEITEM_SUPPLIER]
GO
ALTER TABLE [dbo].[T_F_LINEITEM]  WITH CHECK ADD  CONSTRAINT [FK_T_F_LINEITEM_T_D_LINEITEM] FOREIGN KEY([LINEITEMKEY])
REFERENCES [dbo].[T_D_LINEITEM] ([LINEITEMKEY])
GO
ALTER TABLE [dbo].[T_F_LINEITEM] CHECK CONSTRAINT [FK_T_F_LINEITEM_T_D_LINEITEM]
GO
