ALTER TABLE [dbo].[LINEITEM]  ADD L_LINEITEMKEY INT IDENTITY(1,1)

TRUNCATE TABLE [T_D_LINEITEM];
INSERT INTO [dbo].[T_D_LINEITEM] (
LINEITEMKEY
      ,[QUANTITY]
      ,[EXTENDEDPRICE]
      ,[DISCOUNT]
      ,[TAX]
      ,[RETURNFLAG]
      ,[LINESTATUS]
      ,[SHIPDATE]
      ,[COMMITDATE]
      ,[RECEIPTDATE]
      ,[SHIPINSTRUCT]
      ,[SHIPMODE]
      ,[COMMENT]
      ,[REVENUE]
)
SELECT 
      L_LINEITEMKEY
      ,[L_QUANTITY]
      ,[L_EXTENDEDPRICE]
      ,[L_DISCOUNT]
      ,[L_TAX]
      ,[L_RETURNFLAG]
      ,[L_LINESTATUS]
      ,[L_SHIPDATE]
      ,[L_COMMITDATE]
      ,[L_RECEIPTDATE]
      ,[L_SHIPINSTRUCT]
      ,[L_SHIPMODE]
      ,[L_COMMENT]
      ,(([L_EXTENDEDPRICE]*((1)-[L_DISCOUNT]))*((1)-[L_TAX])) 

  FROM [BEERWULF].[dbo].[LINEITEM];


  TRUNCATE TABLE ST_F_LINEITEM;
  INSERT INTO [dbo].[ST_F_LINEITEM] (
  L_LINEITEMKEY,
  L_LINENUMBER,
  L_ORDERKEY,
  L_PARTKEY,
  L_SUPPKEY   
)
SELECT 
L_LINEITEMKEY,
L_LINENUMBER,
L_ORDERKEY,
L_PARTKEY,
L_SUPPKEY
FROM [BEERWULF].[dbo].[LINEITEM];


INSERT INTO T_F_LINEITEM (LINEITEMKEY,ORDERKEY,PARTKEY,SUPPKEY,CUSTKEY,CUST_REGIONKEY,CUST_NATIONKEY,SUPP_REGIONKEY,SUPP_NATIONKEY,LINENUMBER)
SELECT  LN.LINEITEMKEY,
LI.L_ORDERKEY,LI.L_PARTKEY,LI.L_SUPPKEY,O.O_CUSTKEY,N1.N_REGIONKEY AS CUST_REGIONKEY,C.C_NATIONKEY AS CUST_NATIONKEY,N2.N_REGIONKEY AS SUPP_REGIONKEY,S.S_NATIONKEY AS SUPP_NATIONKEY,LI.L_LINENUMBER
FROM ST_F_LINEITEM AS LI
LEFT JOIN T_D_LINEITEM  AS LN ON LN.LINEITEMKEY = LI.L_LINEITEMKEY 
LEFT JOIN ORDERS   AS O  ON O.O_ORDERKEY  = LI.L_ORDERKEY
LEFT JOIN PARTSUPP AS PS ON PS.PS_PARTKEY = LI.L_PARTKEY   AND PS.PS_SUPPKEY = LI.L_SUPPKEY
LEFT JOIN SUPPLIER AS S  ON S.S_SUPPKEY   = PS.PS_SUPPKEY
LEFT JOIN PART     AS P  ON P.P_PARTKEY   = PS.PS_PARTKEY
LEFT JOIN CUSTOMER AS C  ON C.C_CUSTKEY   = O.O_CUSTKEY
LEFT JOIN NATION   AS N1 ON N1.N_NATIONKEY = C.C_NATIONKEY
LEFT JOIN NATION   AS N2 ON N2.N_NATIONKEY = S.S_NATIONKEY
LEFT JOIN REGION   AS R1 ON R1.R_REGIONKEY = N1.N_REGIONKEY
LEFT JOIN REGION   AS R2 ON R2.R_REGIONKEY = N2.N_REGIONKEY